### ISSUE TITLE
 Login and User Authentication System

### ISSUE THREAD

**Issue by Iamanujosh** [yatulearn/yatulearn#108]
To enhance user personalization and security, I propose the addition of a login and user authentication system. This feature will allow users to create accounts, log in securely

Feature Overview:
User Registration and Login: Add a feature where users can register with an email or through third-party login methods (Google, GitHub, etc.). Once registered, they can log in to access their personalized dashboard.

Secure Authentication: The system should use secure practices, such as hashing passwords and using SSL for secure data transmission.

Personalized User Experience: Logged-in users can have a tailored experience, such as saving favorite books, tracking their reading progress, or seeing personalized recommendations.

Proposed Flow:
Sign-Up Page: Users will register using their email, name, and password, or by connecting with a third-party service (OAuth options like Google or GitHub).
Login Page: Existing users will enter their credentials to log in.
Dashboard: Once logged in, users can access features like their saved books, reading history, and other personalized data.

**Comment by yatulearn** [comment]
ok do it

**Comment by Iamanujosh** [comment]
Thank you

**Comment by ekayZ7875** [comment]
Hello @Iamanujosh i would like to work upon this issue.Please assign it to me.

**Comment by BhavikaPachauri** [comment]
if this issue is open can i work on it
