### ISSUE TITLE
Enhancement of Question Papers Page

### ISSUE THREAD

**Issue by Shariq2003** [yatulearn/yatulearn#118]
The question papers page does not look good at all and it doesn't match with theme of the website, as the website is not upgrading to its next level in all the pages, this page also wants an upgrade in terms of UI and UX.

![image](https://github.com/user-attachments/assets/49ef47bb-d807-45ef-9192-61706b65e452)

For reference to the Notes page, it looks so concise and well structured, similar to the way we have to make question papers page too.

![image](https://github.com/user-attachments/assets/5767d939-d01a-4918-b15d-a7e696c45fa6)

@yatulearn Please assign this to me.
I will be going to update the whole structure of the page and also make it responsive that enhance the UI and UX.

**Comment by arpit74170** [comment]
please assign  this task to me , i will help you out to enhance it with my great skills in website 
I will ad some hover effect and amazing colours in it ,it will look great then

**Comment by Sawan-Kushwah** [comment]
Assign me this task i can do it more better way as i write maintainable code and best UI design possible

**Comment by Shariq2003** [comment]
@yatulearn how can three work on a single task

**Comment by Shariq2003** [comment]
@yatulearn beacuse everyone have their own structure.
Please aasign this to me as I have described what I am going to do

**Comment by yatulearn** [comment]
you all can work on the issue and raise separate pr the best will be merged

**Comment by Sawan-Kushwah** [comment]
@yatulearn assign this issue to anyone of us so that we have surety of getting merge

**Comment by Shariq2003** [comment]
> @yatulearn assign this issue to anyone of us so that we have surety of getting merge

exactly

**Comment by Shariq2003** [comment]
@yatulearn please check PR #240
