### ISSUE TITLE
Error on clicking on the logo in footer

### ISSUE THREAD

**Issue by yatulearn** [yatulearn/yatulearn#134]
there is a issue i.e error comes out after clicking on the logo in the section on every page except home page, can anyone help in fixing it

**Comment by ayush-badola** [comment]
@yatulearn I can fix the issue by editing the footer section in html files. Please assign this issue to me, under GSSoC Extended and Hactoberfest 2024.
Thanks!

**Comment by Divyanshugupta01** [comment]
its issue of path assign  under GSSoC Extended and Hactoberfest 2024  i can
