### ISSUE TITLE
Missing LICENSE and Code of Conduct Files in Root Directory

### ISSUE THREAD

**Issue by rahulgithub-web** [yatulearn/yatulearn#165]
### Title: Missing `LICENSE` and `Code of Conduct` Files in Root Directory

**Describe the bug**
The `LICENSE` and `Code of Conduct` links are present in the README file, but the actual files are missing from the root directory of the project. This causes confusion for contributors and users who try to access the project’s license terms and contribution guidelines.

**To Reproduce**
1. Go to the repository.
2. Scroll to the **License** and **Code of Conduct** sections in the README file.
3. Click on the links to `LICENSE` or `Code of Conduct`.
4. The links return a 404 error or indicate that the files are missing from the root directory.

**Expected behavior**
The `LICENSE` and `Code of Conduct` files should be present in the root directory, and clicking on the links in the README should direct users to the respective files.

**Screenshots**
If applicable, add screenshots to help explain the problem:

![issue](https://github.com/user-attachments/assets/c15d60d6-bf83-4671-b91c-4dca0c45f0a5)

**Desktop (please complete the following information):**
- OS: [e.g. Windows 10, macOS Big Sur]
- Browser: [e.g. Chrome, Firefox]
- Version: [e.g. 114]

**Smartphone (please complete the following information):**
- Device: [e.g. iPhone 12, OnePlus 9]
- OS: [e.g. iOS 15, Android 11]
- Browser: [e.g. Safari, Chrome]
- Version: [e.g. 92]

**Additional context**
I would like to create and add the missing `LICENSE` and `Code of Conduct` files to the root directory to resolve this issue. This will ensure that the links in the README function properly and users can access the necessary documents.

**Comment by yatulearn** [comment]
Kindly check it once

**Comment by rahulgithub-web** [comment]
@yatulearn Kindly review it once and accept the merge request.
