### ISSUE TITLE
Navbar Alignment and NavBar Options Spacing

### ISSUE THREAD

**Issue by rupeshv2121** [yatulearn/yatulearn#184]
Navbar Is slightly down from the top so it give bad User experience also there is need of space between the navbar options.

I take navbar Slightly up and make spacing between the navbar options

![NavBar](https://github.com/user-attachments/assets/f15db1d0-6391-4b52-93d9-bbb353c08569)
![space between options](https://github.com/user-attachments/assets/18ee77ac-720e-4fca-977e-56133be042b9)

Browser - chrome, edge, firefox

**Comment by shivansh023023** [comment]
Hi @rupeshv2121 ca you assign this issue to me
