### ISSUE TITLE
Program Manager - GSSOC Extended

### ISSUE THREAD

**Issue by MastanSayyad** [yatulearn/yatulearn#204]
Hi @yatulearn 

Program Manager this side, I noticed you were using wrong labels (case sensitive), so I have updated the labels to correct one

![image](https://github.com/user-attachments/assets/dda23989-068f-46b4-9d88-532ac3022c33)

**Comment by yatulearn** [comment]
OK thank you

**Comment by MastanSayyad** [comment]
@yatulearn amazing work
