### ISSUE TITLE
Proposal : Adding Scroll to Top button.

### ISSUE THREAD

**Issue by AbhijitMotekar99** [yatulearn/yatulearn#232]
**Is your feature request related to a problem? Please describe.**
Is your feature request related to a problem? Please describe. I’m always frustrated when navigating long pages, especially on mobile devices, because it can be tedious to scroll back to the top manually. Users may find it inconvenient, leading to a less enjoyable browsing experience and potentially causing them to leave the site.

**Describe the solution you'd like**
I propose adding a Scroll to Top button that appears once users scroll down a certain distance on the page. This button should be easily accessible and allow users to quickly return to the top of the page with a single click. The button can have a simple design, such as an upward arrow, and should fade in/out smoothly for better user experience.

**Comment by Madhurimalavathu** [comment]
i want to work on this, can you assign it to me.

**Comment by yatulearn** [comment]
already assigned to someone else who has solved the issue
