### ISSUE TITLE
Web development button is different from others before hover

### ISSUE THREAD

**Issue by nishtha-902** [yatulearn/yatulearn#285]
**Describe the bug**
Web development button is different from others before hover

**To Reproduce**
1. Go to 'https://yatulearn.vercel.app/'
2. Scroll down to 'section before footer'
3. Web development button is different

**Expected behavior**
Web development button must be same as others

**Screenshots**
![image](https://github.com/user-attachments/assets/41abfe30-9b5e-47f1-b9ad-2ff063064c73)

**Comment by Madhurimalavathu** [comment]
i want to work on this issue, can you please assign it to me?
