### ISSUE TITLE
Add more content in AI and ML

### ISSUE THREAD

**Issue by pavitraag** [yatulearn/yatulearn#3]
I would like to add History and Evolution of AI and ML and Ethical Concerns and Challenges in AI as these are must to learn in AIML.Please assign me under gssoc24

**Comment by yatulearn** [comment]
Let’s discuss about it first

**Comment by amanazads** [comment]
We already have the content about ai and ml, so we can modify it and add the new content to the section of ai ml.

**Comment by amanazads** [comment]
Let’s do it
