### ISSUE TITLE
Enhancement - UI for pop up of question papers on hover

### ISSUE THREAD

**Issue by govindumeesala** [yatulearn/yatulearn#42]
Enhancing the pop up of question papers on hovering i
to improve the user experience

![image](https://github.com/user-attachments/assets/c3b44e56-d1d0-47d3-a0de-51c8117e5249)

please assign this to me

**Comment by sambedan1** [comment]
Enhancement Proposal:
I would like to enhance the UI by adding an interactive pop-up for question papers on hover, improving user engagement and accessibility.
Plan:
Implement a sleek, responsive pop-up that shows key details of the question papers when a user hovers over a designated element.
Add smooth hover-triggered animations to create a more intuitive and seamless user experience.
Ensure the pop-up is optimized for various screen sizes and devices, maintaining performance and responsiveness.
I will also provide clear comments within the code to facilitate easy future modifications by other contributors.

so please assign this top me

**Comment by Himanshuch8055** [comment]
@govindumeesala, thank you for your suggestion. We appreciate your message. Once PR no. #43 is merged, we will continue to review this PR. The main issue is major and helpful to others the folder structure.

**Comment by govindumeesala** [comment]
Ok, @Himanshuch8055 
would love to work on it, if assigned

**Comment by Himanshuch8055** [comment]
@govindumeesala, please wait until PR number 43 at https://github.com/yatulearn/yatulearn/pull/43 is merged; after that, you may proceed with your work.

**Comment by sambedan1** [comment]
ok

**Comment by yatulearn** [comment]
Ok do it
