### ISSUE TITLE
Add Multi-Language Support Using Language Translator

### ISSUE THREAD

**Issue by TBorundia** [yatulearn/yatulearn#432]
**Describe the solution you'd like**
Implement a language translation API to allow dynamic switching between multiple languages.
Add a language selector (dropdown or buttons) to the UI for easy language switching.

**Comment by JOSHITHA6** [comment]
I want to solve this issue @yatulearn. Kindly assign me under gssoc'24 extd and hacktoberfest

**Comment by Sahilll15** [comment]
i am working on this @TBorundia
