### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Adityakashyap1011** [yatulearn/yatulearn#45]
There can be a feature of dark mode on the website for the users.

**Comment by yatulearn** [comment]
If you can do it, kindly do it

**Comment by itsaryan917** [comment]
By assigning this issue to me, I’ll ensure the dark mode is intuitive, easy on the eyes, and consistent with the current design. I am confident in delivering a high-quality solution promptly.

Looking forward to contributing!
