### ISSUE TITLE
About Us Page Improvement

### ISSUE THREAD

**Issue by Shariq2003** [yatulearn/yatulearn#46]
![image](https://github.com/user-attachments/assets/8ffafca7-a2e0-462f-8ab6-d66b07ae8ea0)

The About Us page content is unstructured making the page looking so unprofessional.

Please assign this to me, I will improve the whole page.

**Comment by yatulearn** [comment]
Ok do it

**Comment by rounakdey6** [comment]
can you please assign this issue to me

**Comment by Shariq2003** [comment]
@yatulearn i have already raise a PR for this issue, and completed this issue, please mark this as completed after merging my PR and also you have assigned another person for this issue.
I have already completed this.

**Comment by rounakdey6** [comment]
But your PR is not merged yet

**Comment by rounakdey6** [comment]
![image](https://github.com/user-attachments/assets/7756232a-d5b9-4ac2-8954-e05751594db6)
![image](https://github.com/user-attachments/assets/2dd70d6c-ad85-41f8-927b-738cee1d12e8)
@yatulearn have a look .
only thing that i have been facing is merge conflict

**Comment by Shariq2003** [comment]
> But your PR is not merged yet

Because, he also want responsiveness which is an extended task, on which I am working,

**Comment by Shariq2003** [comment]
@yatulearn i have updated the about us page and make it responsive please check PR #68 
and also add the same label of level to this issue as its PR and close this.

**Comment by Shariq2003** [comment]
@yatulearn also update this issue label of level
