### ISSUE TITLE
enhancing the style of topic cards 

### ISSUE THREAD

**Issue by YooAshu** [yatulearn/yatulearn#7]
currently the cards doesn't look good adding some image related to each topic and some hover animations will be good

![Screenshot 2024-10-01 221648](https://github.com/user-attachments/assets/44d2b02d-4d14-49e3-945d-8260f2f9d62a)

**Comment by amanazads** [comment]
Ok let’s do it.

**Comment by rounakdey6** [comment]
can you please assign this issue to me

**Comment by yatulearn** [comment]
> can you please assign this issue to me

assigned
