### ISSUE TITLE
[Feature Request]: Update the styling of sidebar(scrollbar for the entire website that matches with the website theme)

### ISSUE THREAD

**Issue by Shariq2003** [yatulearn/yatulearn#71]
## Is there an existing issue for this?

- [X] I have searched the existing issues

## Feature Description

Modify the scrollbar that mathces the theme of the website and make the whole tab/windows looks user friendly and attractive.

## Use Case

Improve User Experience
Improve UI
Improve the whole website

## ScreenShots

![image](https://github.com/user-attachments/assets/c5ebb9ea-13c6-4517-b4ce-bd1788a9c245)
Sidebar looks weird 

Assign this to me.

**Comment by yatulearn** [comment]
ok

**Comment by rounakdey6** [comment]
please assign this to me

**Comment by Shariq2003** [comment]
@yatulearn please close this issue as completed in #79
