### ISSUE TITLE
Adding the reference link for notes related to that field.

### ISSUE THREAD

**Issue by tarunkumar2005** [yatulearn/yatulearn#78]
**Is your feature request related to a problem? Please describe.**
So i went on the website and if i click on the web development it tells all about it right so we can check how to learn web dev what things are there and all okay so to help the student we can give the reference to the specific notes directly there right at the end of the page means after conclusion that will make it easier to students who wants to learn a specific thing right. this i want to do.

**Describe the solution you'd like**
Already told the soltuion.

So i want to work on this assign me under gssoc-2024-ext and hacktoberfest. @yatulearn

**Comment by yatulearn** [comment]
ok do it

**Comment by tarunkumar2005** [comment]
@yatulearn I have created the pull request you can check it out.
