### ISSUE TITLE
Updation of DSA Course 

### ISSUE THREAD

**Issue by Shariq2003** [yatulearn/yatulearn#87]
The course structute and its content is not well structures and to the point that can't help a student to learn DSA in an efficient manner.
![screencapture-yatulearn-vercel-app-pages-yatu-learn-dsa-html-2024-10-04-01_03_57](https://github.com/user-attachments/assets/387cc58f-52e8-46fc-9e66-a3840e2a686a)

I want to add and update the DSA course completely that can match the latest content and proper data with effective learning.

**Comment by yatulearn** [comment]
ok do it
